[project]
name = "cloud-api"
version = "0.1.0"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]",
  "SQLAlchemy>=2.0",
  "pydantic>=2",
  "pydantic-settings>=2",
  "alembic>=1.13",
  "psycopg[binary]>=3.1"
]
